version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000' # Map frontend port to host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000' # Map backend port to host
    volumes:
      - ./backend:/app  # Mount your backend code directory
    environment:
      - ENV=development
